In [136]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline  
pd.set_option('display.max_columns', None)
from datetime import datetime
plt.style.use('ggplot')
import warnings # current version of seaborn generates a bunch of warnings that we'll ignore
warnings.filterwarnings("ignore")
from IPython.core.display import display, HTML
import seaborn as sns
sns.set(style="whitegrid")

In [142]:
TITLE = ['Position', 'HistCTR', 'IsClick', 'IsUserLoggedOn', 'Price']
SOURCE = "../data/train_sampled.csv"

In [143]:
df = pd.read_csv(SOURCE , sep=',' ) 
#label_frame = df['IsClick']
#df = df.drop(['IsClick'],axis=1)

In [144]:
df.head()

,SearchID,AdID,Position,HistCTR,IsClick,SearchDate,IPID,UserID,IsUserLoggedOn,SearchQuery,SearchLocationID,SearchCategoryID,SearchParams,SearchLocationLevel,SearchRegionID,SearchCityID,SearchCategoryLevel,SearchParentCategoryID,SearchSubcategoryID,UserAgentID,UserAgentOSID,UserDeviceID,UserAgentFamilyID,AdCategoryID,Params,Price,Title,AdCategoryLevel,AdParentCategoryID,AdSubcategoryID
0,121,1220223,7,0.005422,1,2015-05-09 22:21:40.0,490755,3817669,0,NaN,2685,44,NaN,3,9.0,1582.0,3,12,22,1582,44,2014,62,44.0,{223:'Бинокли и телескопы'},1000.0,"Лупа,монокуляр на очковой оправе,Отправка по Р...",3.0,12.0,22.0
1,181,13840581,7,0.013889,1,2015-04-30 10:24:49.0,1507803,2391097,0,NaN,230,22,"{83:'Платья и юбки', 175:'Женская одежда', 90:...",3,2.0,2951.0,3,3,47,63091,20,2014,25,22.0,"{83:'Платья и юбки', 175:'Женская одежда'}",3000.0,Брендовые вечерние платья,3.0,3.0,47.0
2,198,14515103,1,0.033885,1,2015-05-07 10:46:21.0,951832,372668,1,chevrolet cruze,3960,34,"{598:'Для автомобилей', 5:'Запчасти'}",2,18.0,623.0,3,6,7,54509,44,2014,62,34.0,"{5:'Запчасти', 598:'Для автомобилей'}",5470.0,Запчасти б/у и новые для chevrolet cruze (09-),3.0,6.0,7.0
3,404,11801992,1,0.007371,1,2015-04-30 16:48:21.0,130853,2621226,0,NaN,2473,49,NaN,3,14.0,698.0,2,8,45,18318,20,2014,25,46.0,NaN,10419.0,Инкубатор Блиц 48 цифровой,3.0,8.0,40.0
4,438,29135166,1,0.004846,1,2015-05-01 15:48:08.0,599651,2675985,1,NaN,2060,35,NaN,2,44.0,1890.0,3,9,50,10275,20,2014,25,35.0,NaN,878.0,Аэросад Луковое счастье,3.0,9.0,50.0

In [132]:
#that's for bar charts, insert the column name in categorical_columns list for visuaization
categorical_columns = []
for i in categorical_columns:
    plt.figure()
    fig, ax = plt.subplots()
    fig.set_size_inches(15, 6)
    ax =sns.countplot(df[i] )

In [120]:
#df.SearchCategoryID.value_counts()

In [145]:
df.shape

(3438867, 30)

In [146]:
# just to know the size of s string in memory (in bytes)
import sys
sys.getsizeof('3817669')

44

In [147]:
# users_di is the user dictionary that store the number of clicks and non-clicks of user, UserID is its key
users_di = {}
def count_user_clicks(x):
    if not users_di.has_key(x['UserID']):
        users_di[x['UserID']] = {'clicks_no': 0 , 'non_clicks_no': 0 }
    if x['IsClick']==1:
        users_di[x['UserID']]['clicks_no'] += 1 
    else:
        users_di[x['UserID']]['non_clicks_no'] += 1

In [148]:
#read the dataframe by chunk and apply the counting function
for chunk in pd.read_csv(SOURCE, sep=',' , chunksize=100000):
    #print len(users_di)
    chunk.apply(count_user_clicks , axis =1 )

In [113]:
#chunk['UserID'].unique().size

In [149]:
#for testing
users_di[372668]

{'clicks_no': 1, 'non_clicks_no': 3}

In [150]:
# for testing
df.query('UserID == 372668' )

,SearchID,AdID,Position,HistCTR,IsClick,SearchDate,IPID,UserID,IsUserLoggedOn,SearchQuery,SearchLocationID,SearchCategoryID,SearchParams,SearchLocationLevel,SearchRegionID,SearchCityID,SearchCategoryLevel,SearchParentCategoryID,SearchSubcategoryID,UserAgentID,UserAgentOSID,UserDeviceID,UserAgentFamilyID,AdCategoryID,Params,Price,Title,AdCategoryLevel,AdParentCategoryID,AdSubcategoryID
2,198,14515103,1,0.033885,1,2015-05-07 10:46:21.0,951832,372668,1,chevrolet cruze,3960,34,"{598:'Для автомобилей', 5:'Запчасти'}",2,18.0,623.0,3,6,7,54509,44,2014,62,34.0,"{5:'Запчасти', 598:'Для автомобилей'}",5470.0,Запчасти б/у и новые для chevrolet cruze (09-),3.0,6.0,7.0
1433459,46298625,25292381,7,0.000010,0,2015-05-06 13:08:53.0,951832,372668,1,cruze,3960,34,NaN,2,18.0,623.0,3,6,7,54509,44,2014,62,34.0,{5:'Аксессуары'},1424.0,Защита картера Chevrolet Cruze/ Orlando/ Astra,3.0,6.0,7.0
2295839,75248019,34084553,7,0.002880,0,2015-05-12 16:04:42.0,951832,372668,1,NaN,3061,34,"{598:'Для автомобилей', 5:'Запчасти', 817:'Авт...",3,38.0,2469.0,3,6,7,54509,44,2014,62,34.0,"{5:'Запчасти', 598:'Для автомобилей'}",30000.0,Двигатель VW,3.0,6.0,7.0
2658616,89613415,18496042,1,0.006579,0,2015-05-12 15:32:59.0,951832,372668,1,chevrolet cruze,2885,34,"{598:'Для автомобилей', 5:'Запчасти', 817:'Эле...",1,NaN,NaN,3,6,7,54509,44,2014,62,34.0,"{5:'Запчасти', 598:'Для автомобилей'}",3940.0,Запчасти б/у и новые для chevrolet cruze (09-),3.0,6.0,7.0

In [151]:
# function to create the columns based of the created dictionary 
def user_clicks(x):
    return users_di[x]["clicks_no"], users_di[x]["non_clicks_no"] , float(users_di[x]["clicks_no"])\
/(users_di[x]["non_clicks_no"] + users_di[x]["clicks_no"])

In [152]:
df["user_clicks_no"], df["user_non_clicks_no"] , df["user_click_prob"]= zip(*df["UserID"].apply(user_clicks))

In [153]:
df.head()

,SearchID,AdID,Position,HistCTR,IsClick,SearchDate,IPID,UserID,IsUserLoggedOn,SearchQuery,SearchLocationID,SearchCategoryID,SearchParams,SearchLocationLevel,SearchRegionID,SearchCityID,SearchCategoryLevel,SearchParentCategoryID,SearchSubcategoryID,UserAgentID,UserAgentOSID,UserDeviceID,UserAgentFamilyID,AdCategoryID,Params,Price,Title,AdCategoryLevel,AdParentCategoryID,AdSubcategoryID,user_clicks_no,user_non_clicks_no,user_click_prob
0,121,1220223,7,0.005422,1,2015-05-09 22:21:40.0,490755,3817669,0,NaN,2685,44,NaN,3,9.0,1582.0,3,12,22,1582,44,2014,62,44.0,{223:'Бинокли и телескопы'},1000.0,"Лупа,монокуляр на очковой оправе,Отправка по Р...",3.0,12.0,22.0,5,9,0.357143
1,181,13840581,7,0.013889,1,2015-04-30 10:24:49.0,1507803,2391097,0,NaN,230,22,"{83:'Платья и юбки', 175:'Женская одежда', 90:...",3,2.0,2951.0,3,3,47,63091,20,2014,25,22.0,"{83:'Платья и юбки', 175:'Женская одежда'}",3000.0,Брендовые вечерние платья,3.0,3.0,47.0,5,11,0.312500
2,198,14515103,1,0.033885,1,2015-05-07 10:46:21.0,951832,372668,1,chevrolet cruze,3960,34,"{598:'Для автомобилей', 5:'Запчасти'}",2,18.0,623.0,3,6,7,54509,44,2014,62,34.0,"{5:'Запчасти', 598:'Для автомобилей'}",5470.0,Запчасти б/у и новые для chevrolet cruze (09-),3.0,6.0,7.0,1,3,0.250000
3,404,11801992,1,0.007371,1,2015-04-30 16:48:21.0,130853,2621226,0,NaN,2473,49,NaN,3,14.0,698.0,2,8,45,18318,20,2014,25,46.0,NaN,10419.0,Инкубатор Блиц 48 цифровой,3.0,8.0,40.0,1,1,0.500000
4,438,29135166,1,0.004846,1,2015-05-01 15:48:08.0,599651,2675985,1,NaN,2060,35,NaN,2,44.0,1890.0,3,9,50,10275,20,2014,25,35.0,NaN,878.0,Аэросад Луковое счастье,3.0,9.0,50.0,10,9,0.526316

In [121]:
#storing the dictionary on disk
import pickle

with open('../data/users_di.pickle', 'wb') as handle:
  pickle.dump(users_di, handle)

with open('../data/users_di.pickle', 'rb') as handle:
  users_di2 = pickle.load(handle)

print users_di2 == users_di

True

In [127]:
#creating the time related features
df['SearchDate'] = pd.to_datetime(df['SearchDate'])

In [105]:
df['day_of_week'] = df['SearchDate'].dt.dayofweek
df['hour'] = df['SearchDate'].dt.hour

In [117]:
#df = df.drop(['weekday'], axis =1)
df.head()

,SearchID,AdID,Position,HistCTR,IsClick,SearchDate,IPID,UserID,IsUserLoggedOn,SearchQuery,SearchLocationID,SearchCategoryID,SearchParams,SearchLocationLevel,SearchRegionID,SearchCityID,SearchCategoryLevel,SearchParentCategoryID,SearchSubcategoryID,UserAgentID,UserAgentOSID,UserDeviceID,UserAgentFamilyID,AdCategoryID,Params,Price,Title,AdCategoryLevel,AdParentCategoryID,AdSubcategoryID,user_clicks_no,user_non_clicks_no,user_click_prob,hour,day_of_week
0,121,1220223,7,0.005422,1,2015-05-09 22:21:40,490755,3817669,0,NaN,2685,44,NaN,3,9.0,1582.0,3,12,22,1582,44,2014,62,44.0,{223:'Бинокли и телескопы'},1000.0,"Лупа,монокуляр на очковой оправе,Отправка по Р...",3.0,12.0,22.0,5,9,0.357143,22,5
1,181,13840581,7,0.013889,1,2015-04-30 10:24:49,1507803,2391097,0,NaN,230,22,"{83:'Платья и юбки', 175:'Женская одежда', 90:...",3,2.0,2951.0,3,3,47,63091,20,2014,25,22.0,"{83:'Платья и юбки', 175:'Женская одежда'}",3000.0,Брендовые вечерние платья,3.0,3.0,47.0,5,11,0.312500,10,3
2,198,14515103,1,0.033885,1,2015-05-07 10:46:21,951832,372668,1,chevrolet cruze,3960,34,"{598:'Для автомобилей', 5:'Запчасти'}",2,18.0,623.0,3,6,7,54509,44,2014,62,34.0,"{5:'Запчасти', 598:'Для автомобилей'}",5470.0,Запчасти б/у и новые для chevrolet cruze (09-),3.0,6.0,7.0,1,3,0.250000,10,3
3,404,11801992,1,0.007371,1,2015-04-30 16:48:21,130853,2621226,0,NaN,2473,49,NaN,3,14.0,698.0,2,8,45,18318,20,2014,25,46.0,NaN,10419.0,Инкубатор Блиц 48 цифровой,3.0,8.0,40.0,1,1,0.500000,16,3
4,438,29135166,1,0.004846,1,2015-05-01 15:48:08,599651,2675985,1,NaN,2060,35,NaN,2,44.0,1890.0,3,9,50,10275,20,2014,25,35.0,NaN,878.0,Аэросад Луковое счастье,3.0,9.0,50.0,10,9,0.526316,15,4

In [188]:
# search_di is the search query dictionary that store the number of regular, highlighted, context ads, SearchID is its key
search_di = {}
def count_search_ads(x):
    if not search_di.has_key(x['SearchID']):
        search_di[x['SearchID']] = {'regular_no': 0 , 'highlighted_no': 0 , 'context_no': 0 }
    if x['ObjectType']==1:
        search_di[x['SearchID']]['regular_no'] += 1 
    elif x['ObjectType']==2:
        search_di[x['SearchID']]['highlighted_no'] += 1 
    else:
        search_di[x['SearchID']]['context_no'] += 1

In [195]:
#read the dataframe by chunk and apply the counting function
SOURCE2 = "../data/testSearchStream.tsv"
for chunk in pd.read_csv(SOURCE2, sep='\t', nrows=100000 , chunksize=100000):
    #print len(search_di)
    chunk.apply(count_search_ads , axis =1 )

NotImplementedError: 'nrows' and 'chunksize' cannot be used together yet.

In [193]:
search_di[1]

{'context_no': 6, 'highlighted_no': 0, 'regular_no': 9}